name: Build and Lint Checks 

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: latest
    - name: Turbo
      run: npm install turbo --global
    - name: Install
      run: pnpm install
    - name: Build
      run: turbo build

  Windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: latest
    - name: Turbo
      run: npm install turbo --global
    - name: Install
      run: pnpm install
    - name: Build
      run: turbo build
